# -*- coding: utf-8 -*-
"""Beher_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2_JRg3paAgvzTUThL7zeQm7PfrUx3C_
"""

import streamlit as st

from finder import find_beher

st.title(" 🖋️Hindi Beher Recognizer")

text = st.text_area("Enter Shayari")

if st.button("Recognize"):

    beher, pattern = find_beher(text)

    st.success("Detected Beher")

    st.write(beher)

    st.write("Pattern")

    st.code(pattern)
