# -*- coding: utf-8 -*-
"""Beher_Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKcCE2avMgxtje7KKeS79eLQFPg3Ft3i
"""

BEHERS = {
    "Bahar-e-Ramal": "2122 2122 2122 212",
    "Bahar-e-Hazaj": "2212 2212 2212 2212",
    "Bahar-e-Kamil": "2221 2221 2221",
    "Bahar-e-Mutaqarib": "1222 1222 1222 122",
    "Bahar-e-Mutaadarik": "1212 1212 1212",
    "Bahar-e-Rajaz": "221 221 221",
    "Bahar-e-Mujtass": "21221 21221",
    "Bahar-e-Khafif": "21212 21212",
    "Bahar-e-Saree": "22122 22122",
    "Bahar-e-Munsarih": "221221 221221"
}