# -*- coding: utf-8 -*-
"""finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPUSl3-NUlgQx9cqUTpgUg1I81ifyd1r
"""

from beher_database import BEHERS
from meter import generate_pattern

def find_beher(text):
    # Generate the pattern from the input text
    pattern = generate_pattern(text)

    best_beher = None
    best_score = -1

    # Compare with each beher pattern
    for beher_name, beher_pattern in BEHERS.items():

        # Compare character by character
        matches = sum(
            1
            for a, b in zip(pattern, beher_pattern)
            if a == b
        )

        # Keep the best match
        if matches > best_score:
            best_score = matches
            best_beher = beher_name

    return best_beher, pattern