# -*- coding: utf-8 -*-
"""meter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1y0-4Mdwu7bvCwWiq9OsqYq62geDEaf
"""

import re

def generate_pattern(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z\u0900-\u097F\u0600-\u06FF ]', '', text)

    vowels = "aeiouअआइईउऊएऐओऔ"

    pattern = ""

    for ch in text:

        if ch in vowels:
            pattern += "2"
        elif ch == " ":
            pattern += " "
        else:
            pattern += "1"

    return pattern